In [1]:
import pandas as pd
df = pd.read_csv('insurance.csv')

In [2]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
..  ...            ...               ...
77   22              2                 1
78   22              2                 1
79   22              2                 1
80   22              2                 1
81   21              2                 1

[82 rows x 3 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('bought_insurance', axis='columns'), df.bought_insurance)

In [6]:
x_train

age  affordibility
32   35              1
25   54              1
76   23              2
49   30              1
79   22              2
..  ...            ...
36   34              1
2    47              1
29   36              1
34   34              1
54   29              1

[61 rows x 2 columns]

In [7]:
y_train

32    1
25    1
76    1
49    1
79    1
     ..
36    1
2     1
29    1
34    1
54    1
Name: bought_insurance, Length: 61, dtype: int64

In [8]:
x_test

age  affordibility
69   25              1
75   23              2
60   27              1
70   24              1
13   29              0
35   34              1
5    56              1
80   22              2
33   35              1
8    62              1
7    60              0
27   46              1
21   26              0
38   33              1
63   26              1
53   29              1
12   27              0
30   35              1
52   29              1
73   23              1
50   30              1

In [9]:
x_train['age'] = x_train['age']/100
x_test['age'] = x_test['age']/100

In [10]:
x_train.head()

age  affordibility
32  0.35              1
25  0.54              1
76  0.23              2
49  0.30              1
79  0.22              2

In [11]:
from tensorflow import keras

In [12]:
model = keras.Sequential(
    [keras.layers.Dense(1, input_shape=(2,), activation= 'sigmoid', bias_initializer = 'zeros')]
)

C:\Users\rohit\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.compile(optimizer= 'adam', loss ='binary_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs =1000)

Epoch 1/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1614 - loss: 1.6259  
Epoch 2/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1510 - loss: 1.6325 
Epoch 3/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1718 - loss: 1.5804 
Epoch 4/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1510 - loss: 1.6213 
Epoch 5/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1510 - loss: 1.6156 
Epoch 6/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1926 - loss: 1.5599 
Epoch 7/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1510 - loss: 1.6088 
Epoch 8/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1614 - loss: 1.5825 
Epoch 9/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1614 - loss: 1.6018 
Epoch 10/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1405 - loss: 1.6199 
Epoch 11/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1614 - loss: 1.5980 
Epoch 12/1000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy:

In [15]:
model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8095 - loss: 0.4710


[0.47096267342567444, 0.8095238208770752]

In [16]:
model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.78783387],
       [0.812354  ],
       [0.7874527 ],
       [0.7880243 ],
       [0.7606374 ],
       [0.7861147 ],
       [0.78186953],
       [0.81252766],
       [0.785923  ],
       [0.7807013 ],
       [0.7541471 ],
       [0.7838066 ],
       [0.76125926],
       [0.7863062 ],
       [0.7876434 ],
       [0.78707105],
       [0.76105213],
       [0.785923  ],
       [0.78707105],
       [0.78821456],
       [0.78688   ]], dtype=float32)

In [17]:
y_test

69    1
75    1
60    1
70    1
13    0
35    1
5     1
80    1
33    1
8     1
7     1
27    0
21    0
38    1
63    1
53    1
12    0
30    1
52    1
73    1
50    1
Name: bought_insurance, dtype: int64

In [18]:
coef, intercept = model.get_weights()

In [19]:
coef

array([[-0.1139457 ],
       [ 0.15118249]], dtype=float32)

In [20]:
intercept

array([1.1892216], dtype=float32)

In [21]:
coef[0]

array([-0.1139457], dtype=float32)

In [22]:
coef[0][0]

-0.1139457

In [23]:
coef[1]

array([0.15118249], dtype=float32)

In [24]:
import numpy as np
def sigmoid(x):
    return(1/(1+np.exp(-x)))

In [25]:
def pred_f(age, affordability):
    summa = coef[0]*age + coef[1]*affordability + intercept
    return(sigmoid(summa))

In [27]:
pred_f(0.17, 1)

array([0.78935355], dtype=float32)